SELECT * FROM TRANSCRIPT WHERE id=201751893;

SELECT * FROM TRANSCRIPT_STUDENT_TERMS WHERE STUDENT_RECORD_ID=201751893;

SELECT COURSE.ID, COURSE.CODE, COURSE.CREDITS, COURSE.GRADE_POINT, TERM.TERM_GPA, TERM.NAME  FROM TERM
INNER JOIN TRANSCRIPT_STUDENT_TERMS
ON TERM.ID=STUDENT_TERMS_ID
INNER JOIN TERM_TERM_COURSES
ON TERM_TERM_COURSES.STUDENT_TERM_ID=TERM.ID
JOIN COURSE
ON COURSE.ID=TERM_TERM_COURSES.TERM_COURSES_ID
WHERE STUDENT_RECORD_ID=201751893;
