SELECT *
FROM TRANSCRIPT_STUDENT_TERMS
WHERE STUDENT_RECORD_ID = 201751893;

SELECT *
FROM TERM_TERM_COURSES
JOIN TRANSCRIPT_STUDENT_TERMS
ON TRANSCRIPT_STUDENT_TERMS.STUDENT_TERMS_ID = TERM_TERM_COURSES.STUDENT_TERM_ID
WHERE STUDENT_RECORD_ID = 201751893;

SELECT * FROM COURSE
INNER JOIN TERM_TERM_COURSES
ON COURSE.ID = TERM_TERM_COURSES.TERM_COURSES_ID
JOIN TRANSCRIPT_STUDENT_TERMS
ON TRANSCRIPT_STUDENT_TERMS.STUDENT_TERMS_ID = TERM_TERM_COURSES.STUDENT_TERM_ID
WHERE STUDENT_RECORD_ID = 201751893;

SELECT
NAME,
TERM_GPA, CREDITS_GRADED_THIS_TERM, GRADE_POINTS_THIS_TERM,
TERM_CUMULATIVE_GPA, CREDITS_GRADED_CUMULATIVE, GRADE_POINTS_CUMULATIVE,
CREDITS_GRADED_TOTAL, GRADE_POINTS_TOTAL,
CREDITS_ENROLLED_THIS_TERM,
FROM TERM
JOIN TRANSCRIPT_STUDENT_TERMS
ON TERM.ID = TRANSCRIPT_STUDENT_TERMS.STUDENT_TERMS_ID
WHERE TRANSCRIPT_STUDENT_TERMS.STUDENT_RECORD_ID = 201751893;

SELECT *  FROM TERM
JOIN TRANSCRIPT_STUDENT_TERMS
ON TERM.ID = TRANSCRIPT_STUDENT_TERMS.STUDENT_TERMS_ID
WHERE TRANSCRIPT_STUDENT_TERMS.STUDENT_RECORD_ID = 201751893;

SELECT * FROM COURSE
JOIN TERM_TERM_COURSES
ON COURSE.ID = TERM_TERM_COURSES.TERM_COURSES_ID
WHERE TERM_TERM_COURSES.STUDENT_TERM_ID = 4974;

SELECT * FROM TRANSCRIPT WHERE TRANSCRIPT.ID = 201751893;